### ISSUE TITLE
Extending default_hash

### ISSUE THREAD

**Issue by blelump** [trailblazer/formular#10]
Hi @fran-worley ,

I wonder what would be best way to extend an already defined element attribute. Lets assume that `BaseForm` is given:

```
  BaseForm = Class.new(Formular::Elements::Form) do
    set_default :class, %w(form-horizontal)
  end
```

Now I'd like to extend its behaviour and add some specialized properties, eg. another class. [`set_default`](https://github.com/trailblazer/formular/blob/41ec5242c9a11c09477bcb01ad59431b1521ab7e/lib/formular/element.rb#L28) always overrides property and thus so far the only way of doing this (or at least I am unable to find any other) is to call `default_hash` explicitly:

```
    class DocForm < BaseForm
      set_default :enctype, "multipart/form-data"
      default_hash[:class][:value] << 'form-hacky'
    end
```

It works, but seems to be quite hacky... The problem (or just the way it works?) with `set_default` is that it always _sets_ (and overrides if smth already exists), whereas we utilize inheritance advantages so that `set_default` in such case seems to be not enough. I don't have any shiny solution yet, because simply assuming that:

```
    def self.set_default(key, value, conditions = {})
      # note memoization
      self.default_hash[key] ||= { value: value, condition: conditions }
    end
```

introduces another problems.

**Comment by fran-worley** [comment]
Yeah I had that originally, however in keeping with expected inheritance behaviour defining something again should 'override' what was there originally.

I agree that this causes issues with classes or anything where you might want to append to rather than override.

Is your problem specific to classes or do you have other examples?

With classes I was looking into a way of having add_class, remove_class or something like that...

**Comment by fran-worley** [comment]
I've been thinking about this. What if we added an optional param to set default for the method/ operator you wanted to use to 'set' it?

```ruby
class SomeFancyElement < SomeOtherElement
  set_default :value, 'some value' # works without a method just fine as it defaults to '='
  set_default :class, 'file-field', method: :<<, if: :file_field?  # if you provide a method, it will use that
end
```

**Comment by fran-worley** [comment]
We would need to consider the implication of conditions as you'd still be overriding those if you did the above, but maybe we go with that for now and see how we get on. 

I'm keen not to expand the API too much too soon.

**Comment by blelump** [comment]
@fran-worley , 

honestly I tend to be sceptical about such solution. On one hand it's really powerful, but there's dark side which may result in abuses of using it. I think we shouldn't expand `set_default` to the level, where any possible method can be used. It's flexible, but way too much.

Answering your previous question, yep this mostly concerns `class` attribute. Currently I dont have idea for any other use case.

**Comment by fran-worley** [comment]
Fair point. Highlighting further why I should code at 6am without coffee ☕  😆 

If it's just classes, what about treating them separately and providing the following class methods for convenience?

```ruby
# just providing for convenience and consistency, you could just use set_default if you wanted
def self.set_default_class(*classes, **condition)
  set_default(:class, classes, condition)
end

# adds a class to the existing class array
def self.add_default_class(*classes, **condition)
  classes += default_hash[:class]
  set_default(:class, classes, condition)
end
 
# removes a class from the existing class array
def self.remove_default_class(*classes, **condition)
  classes -= default_hash[:class]
  set_default(:class, classes, condition)
end
```

**Comment by fran-worley** [comment]
@blelump I've decided against this in favour of making better use of the default API and process_value API. 

Take your example of a form with `form-horizontal` as a default. Rather than remove the default class, I would have horizontal as a boolean option on the element class and if true, append the relevant class to the html attribute.

That way you can easily override it per element instance by setting `horizontal: true`. See [this commit](https://github.com/trailblazer/formular/commit/027dc685f198c4cbf76a0163620d4c0fd1adbf2d) for an example like this done with buttons.
