### ISSUE TITLE
Checkbox element is not selected when it should

### ISSUE THREAD

**Issue by Titinux** [trailblazer/formular#41]
*I'm using formular master branch*

```ruby
f.checkbox(:is_public)
```
with form object responding to is_public with true or false the checkbox is never checked. I have probably misunderstand something but I don't know what.

**Comment by emaglio** [comment]
You need to pass the value in order to match the `checked` status.
For example:
`f.checked :is_public, value: true`
This will be checked only if `model.is_public == true`

[Here](https://github.com/trailblazer/formular/blob/master/test/slim_test.rb#L28) a test, it's not super readable but it works. 

hope this makes sense

**Comment by fran-worley** [comment]
Would it be sensible to have true as the default value? It's commonly used as a boolean field...

**Comment by Titinux** [comment]
👍 @emaglio It works great, thanks.

@fran-worley I think true would be a better default value. Documentation would have really helped on this problem. If you write a global documentation structure I would be pleased to fill it with articles about elements.

**Comment by emaglio** [comment]
We are working on the documents...we should have something soon!
